// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "lenet.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_lv<32> lenet::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_logic lenet::ap_const_logic_0 = sc_dt::Log_0;
const sc_logic lenet::ap_const_logic_1 = sc_dt::Log_1;

lenet::lenet(sc_module_name name) : sc_module(name), mVcdFile(0) {
    AXI_DMA_SLAVE_U0 = new AXI_DMA_SLAVE("AXI_DMA_SLAVE_U0");
    AXI_DMA_SLAVE_U0->ap_clk(ap_clk);
    AXI_DMA_SLAVE_U0->ap_rst(ap_rst_n_inv);
    AXI_DMA_SLAVE_U0->ap_start(AXI_DMA_SLAVE_U0_ap_start);
    AXI_DMA_SLAVE_U0->start_full_n(start_for_SCIG_1_U0_full_n);
    AXI_DMA_SLAVE_U0->ap_done(AXI_DMA_SLAVE_U0_ap_done);
    AXI_DMA_SLAVE_U0->ap_continue(AXI_DMA_SLAVE_U0_ap_continue);
    AXI_DMA_SLAVE_U0->ap_idle(AXI_DMA_SLAVE_U0_ap_idle);
    AXI_DMA_SLAVE_U0->ap_ready(AXI_DMA_SLAVE_U0_ap_ready);
    AXI_DMA_SLAVE_U0->start_out(AXI_DMA_SLAVE_U0_start_out);
    AXI_DMA_SLAVE_U0->start_write(AXI_DMA_SLAVE_U0_start_write);
    AXI_DMA_SLAVE_U0->in_stream_TDATA(in_stream_TDATA);
    AXI_DMA_SLAVE_U0->in_stream_TVALID(in_stream_TVALID);
    AXI_DMA_SLAVE_U0->in_stream_TREADY(AXI_DMA_SLAVE_U0_in_stream_TREADY);
    AXI_DMA_SLAVE_U0->in_stream_TLAST(in_stream_TLAST);
    AXI_DMA_SLAVE_U0->out_stream_V_V_din(AXI_DMA_SLAVE_U0_out_stream_V_V_din);
    AXI_DMA_SLAVE_U0->out_stream_V_V_full_n(connect_0_V_V_full_n);
    AXI_DMA_SLAVE_U0->out_stream_V_V_write(AXI_DMA_SLAVE_U0_out_stream_V_V_write);
    SCIG_1_U0 = new SCIG_1("SCIG_1_U0");
    SCIG_1_U0->ap_clk(ap_clk);
    SCIG_1_U0->ap_rst(ap_rst_n_inv);
    SCIG_1_U0->ap_start(SCIG_1_U0_ap_start);
    SCIG_1_U0->start_full_n(start_for_SMM_1u_25u_20u_U0_full_n);
    SCIG_1_U0->ap_done(SCIG_1_U0_ap_done);
    SCIG_1_U0->ap_continue(SCIG_1_U0_ap_continue);
    SCIG_1_U0->ap_idle(SCIG_1_U0_ap_idle);
    SCIG_1_U0->ap_ready(SCIG_1_U0_ap_ready);
    SCIG_1_U0->start_out(SCIG_1_U0_start_out);
    SCIG_1_U0->start_write(SCIG_1_U0_start_write);
    SCIG_1_U0->in_V_V_dout(connect_0_V_V_dout);
    SCIG_1_U0->in_V_V_empty_n(connect_0_V_V_empty_n);
    SCIG_1_U0->in_V_V_read(SCIG_1_U0_in_V_V_read);
    SCIG_1_U0->out_V_V_din(SCIG_1_U0_out_V_V_din);
    SCIG_1_U0->out_V_V_full_n(connect_1_V_V_full_n);
    SCIG_1_U0->out_V_V_write(SCIG_1_U0_out_V_V_write);
    SMM_1u_25u_20u_U0 = new SMM_1u_25u_20u_s("SMM_1u_25u_20u_U0");
    SMM_1u_25u_20u_U0->ap_clk(ap_clk);
    SMM_1u_25u_20u_U0->ap_rst(ap_rst_n_inv);
    SMM_1u_25u_20u_U0->ap_start(SMM_1u_25u_20u_U0_ap_start);
    SMM_1u_25u_20u_U0->start_full_n(start_for_pool_2u_20u_24u_U0_full_n);
    SMM_1u_25u_20u_U0->ap_done(SMM_1u_25u_20u_U0_ap_done);
    SMM_1u_25u_20u_U0->ap_continue(SMM_1u_25u_20u_U0_ap_continue);
    SMM_1u_25u_20u_U0->ap_idle(SMM_1u_25u_20u_U0_ap_idle);
    SMM_1u_25u_20u_U0->ap_ready(SMM_1u_25u_20u_U0_ap_ready);
    SMM_1u_25u_20u_U0->start_out(SMM_1u_25u_20u_U0_start_out);
    SMM_1u_25u_20u_U0->start_write(SMM_1u_25u_20u_U0_start_write);
    SMM_1u_25u_20u_U0->in_stream_a_V_V_dout(connect_1_V_V_dout);
    SMM_1u_25u_20u_U0->in_stream_a_V_V_empty_n(connect_1_V_V_empty_n);
    SMM_1u_25u_20u_U0->in_stream_a_V_V_read(SMM_1u_25u_20u_U0_in_stream_a_V_V_read);
    SMM_1u_25u_20u_U0->out_stream_V_V_din(SMM_1u_25u_20u_U0_out_stream_V_V_din);
    SMM_1u_25u_20u_U0->out_stream_V_V_full_n(connect_2_V_V_full_n);
    SMM_1u_25u_20u_U0->out_stream_V_V_write(SMM_1u_25u_20u_U0_out_stream_V_V_write);
    pool_2u_20u_24u_U0 = new pool_2u_20u_24u_s("pool_2u_20u_24u_U0");
    pool_2u_20u_24u_U0->ap_clk(ap_clk);
    pool_2u_20u_24u_U0->ap_rst(ap_rst_n_inv);
    pool_2u_20u_24u_U0->ap_start(pool_2u_20u_24u_U0_ap_start);
    pool_2u_20u_24u_U0->start_full_n(start_for_SCIG_U0_full_n);
    pool_2u_20u_24u_U0->ap_done(pool_2u_20u_24u_U0_ap_done);
    pool_2u_20u_24u_U0->ap_continue(pool_2u_20u_24u_U0_ap_continue);
    pool_2u_20u_24u_U0->ap_idle(pool_2u_20u_24u_U0_ap_idle);
    pool_2u_20u_24u_U0->ap_ready(pool_2u_20u_24u_U0_ap_ready);
    pool_2u_20u_24u_U0->start_out(pool_2u_20u_24u_U0_start_out);
    pool_2u_20u_24u_U0->start_write(pool_2u_20u_24u_U0_start_write);
    pool_2u_20u_24u_U0->in_V_V_dout(connect_2_V_V_dout);
    pool_2u_20u_24u_U0->in_V_V_empty_n(connect_2_V_V_empty_n);
    pool_2u_20u_24u_U0->in_V_V_read(pool_2u_20u_24u_U0_in_V_V_read);
    pool_2u_20u_24u_U0->out_V_V_din(pool_2u_20u_24u_U0_out_V_V_din);
    pool_2u_20u_24u_U0->out_V_V_full_n(connect_3_V_V_full_n);
    pool_2u_20u_24u_U0->out_V_V_write(pool_2u_20u_24u_U0_out_V_V_write);
    SCIG_U0 = new SCIG("SCIG_U0");
    SCIG_U0->ap_clk(ap_clk);
    SCIG_U0->ap_rst(ap_rst_n_inv);
    SCIG_U0->ap_start(SCIG_U0_ap_start);
    SCIG_U0->start_full_n(start_for_SMM_1u_500u_50u_U0_full_n);
    SCIG_U0->ap_done(SCIG_U0_ap_done);
    SCIG_U0->ap_continue(SCIG_U0_ap_continue);
    SCIG_U0->ap_idle(SCIG_U0_ap_idle);
    SCIG_U0->ap_ready(SCIG_U0_ap_ready);
    SCIG_U0->start_out(SCIG_U0_start_out);
    SCIG_U0->start_write(SCIG_U0_start_write);
    SCIG_U0->in_V_V_dout(connect_3_V_V_dout);
    SCIG_U0->in_V_V_empty_n(connect_3_V_V_empty_n);
    SCIG_U0->in_V_V_read(SCIG_U0_in_V_V_read);
    SCIG_U0->out_V_V_din(SCIG_U0_out_V_V_din);
    SCIG_U0->out_V_V_full_n(connect_4_V_V_full_n);
    SCIG_U0->out_V_V_write(SCIG_U0_out_V_V_write);
    SMM_1u_500u_50u_U0 = new SMM_1u_500u_50u_s("SMM_1u_500u_50u_U0");
    SMM_1u_500u_50u_U0->ap_clk(ap_clk);
    SMM_1u_500u_50u_U0->ap_rst(ap_rst_n_inv);
    SMM_1u_500u_50u_U0->ap_start(SMM_1u_500u_50u_U0_ap_start);
    SMM_1u_500u_50u_U0->start_full_n(start_for_pool_2u_50u_8u_U0_full_n);
    SMM_1u_500u_50u_U0->ap_done(SMM_1u_500u_50u_U0_ap_done);
    SMM_1u_500u_50u_U0->ap_continue(SMM_1u_500u_50u_U0_ap_continue);
    SMM_1u_500u_50u_U0->ap_idle(SMM_1u_500u_50u_U0_ap_idle);
    SMM_1u_500u_50u_U0->ap_ready(SMM_1u_500u_50u_U0_ap_ready);
    SMM_1u_500u_50u_U0->start_out(SMM_1u_500u_50u_U0_start_out);
    SMM_1u_500u_50u_U0->start_write(SMM_1u_500u_50u_U0_start_write);
    SMM_1u_500u_50u_U0->in_stream_a_V_V_dout(connect_4_V_V_dout);
    SMM_1u_500u_50u_U0->in_stream_a_V_V_empty_n(connect_4_V_V_empty_n);
    SMM_1u_500u_50u_U0->in_stream_a_V_V_read(SMM_1u_500u_50u_U0_in_stream_a_V_V_read);
    SMM_1u_500u_50u_U0->out_stream_V_V_din(SMM_1u_500u_50u_U0_out_stream_V_V_din);
    SMM_1u_500u_50u_U0->out_stream_V_V_full_n(connect_5_V_V_full_n);
    SMM_1u_500u_50u_U0->out_stream_V_V_write(SMM_1u_500u_50u_U0_out_stream_V_V_write);
    pool_2u_50u_8u_U0 = new pool_2u_50u_8u_s("pool_2u_50u_8u_U0");
    pool_2u_50u_8u_U0->ap_clk(ap_clk);
    pool_2u_50u_8u_U0->ap_rst(ap_rst_n_inv);
    pool_2u_50u_8u_U0->ap_start(pool_2u_50u_8u_U0_ap_start);
    pool_2u_50u_8u_U0->start_full_n(start_for_FC_1u_800u_500u_U0_full_n);
    pool_2u_50u_8u_U0->ap_done(pool_2u_50u_8u_U0_ap_done);
    pool_2u_50u_8u_U0->ap_continue(pool_2u_50u_8u_U0_ap_continue);
    pool_2u_50u_8u_U0->ap_idle(pool_2u_50u_8u_U0_ap_idle);
    pool_2u_50u_8u_U0->ap_ready(pool_2u_50u_8u_U0_ap_ready);
    pool_2u_50u_8u_U0->start_out(pool_2u_50u_8u_U0_start_out);
    pool_2u_50u_8u_U0->start_write(pool_2u_50u_8u_U0_start_write);
    pool_2u_50u_8u_U0->in_V_V_dout(connect_5_V_V_dout);
    pool_2u_50u_8u_U0->in_V_V_empty_n(connect_5_V_V_empty_n);
    pool_2u_50u_8u_U0->in_V_V_read(pool_2u_50u_8u_U0_in_V_V_read);
    pool_2u_50u_8u_U0->out_V_V_din(pool_2u_50u_8u_U0_out_V_V_din);
    pool_2u_50u_8u_U0->out_V_V_full_n(connect_6_V_V_full_n);
    pool_2u_50u_8u_U0->out_V_V_write(pool_2u_50u_8u_U0_out_V_V_write);
    FC_1u_800u_500u_U0 = new FC_1u_800u_500u_s("FC_1u_800u_500u_U0");
    FC_1u_800u_500u_U0->ap_clk(ap_clk);
    FC_1u_800u_500u_U0->ap_rst(ap_rst_n_inv);
    FC_1u_800u_500u_U0->ap_start(FC_1u_800u_500u_U0_ap_start);
    FC_1u_800u_500u_U0->start_full_n(start_for_FC_1u_500u_10u_U0_full_n);
    FC_1u_800u_500u_U0->ap_done(FC_1u_800u_500u_U0_ap_done);
    FC_1u_800u_500u_U0->ap_continue(FC_1u_800u_500u_U0_ap_continue);
    FC_1u_800u_500u_U0->ap_idle(FC_1u_800u_500u_U0_ap_idle);
    FC_1u_800u_500u_U0->ap_ready(FC_1u_800u_500u_U0_ap_ready);
    FC_1u_800u_500u_U0->start_out(FC_1u_800u_500u_U0_start_out);
    FC_1u_800u_500u_U0->start_write(FC_1u_800u_500u_U0_start_write);
    FC_1u_800u_500u_U0->in_stream_a_V_V_dout(connect_6_V_V_dout);
    FC_1u_800u_500u_U0->in_stream_a_V_V_empty_n(connect_6_V_V_empty_n);
    FC_1u_800u_500u_U0->in_stream_a_V_V_read(FC_1u_800u_500u_U0_in_stream_a_V_V_read);
    FC_1u_800u_500u_U0->out_stream_V_V_din(FC_1u_800u_500u_U0_out_stream_V_V_din);
    FC_1u_800u_500u_U0->out_stream_V_V_full_n(connect_7_V_V_full_n);
    FC_1u_800u_500u_U0->out_stream_V_V_write(FC_1u_800u_500u_U0_out_stream_V_V_write);
    FC_1u_500u_10u_U0 = new FC_1u_500u_10u_s("FC_1u_500u_10u_U0");
    FC_1u_500u_10u_U0->ap_clk(ap_clk);
    FC_1u_500u_10u_U0->ap_rst(ap_rst_n_inv);
    FC_1u_500u_10u_U0->ap_start(FC_1u_500u_10u_U0_ap_start);
    FC_1u_500u_10u_U0->start_full_n(start_for_AXI_DMA_MASTER_U0_full_n);
    FC_1u_500u_10u_U0->ap_done(FC_1u_500u_10u_U0_ap_done);
    FC_1u_500u_10u_U0->ap_continue(FC_1u_500u_10u_U0_ap_continue);
    FC_1u_500u_10u_U0->ap_idle(FC_1u_500u_10u_U0_ap_idle);
    FC_1u_500u_10u_U0->ap_ready(FC_1u_500u_10u_U0_ap_ready);
    FC_1u_500u_10u_U0->start_out(FC_1u_500u_10u_U0_start_out);
    FC_1u_500u_10u_U0->start_write(FC_1u_500u_10u_U0_start_write);
    FC_1u_500u_10u_U0->in_stream_a_V_V_dout(connect_7_V_V_dout);
    FC_1u_500u_10u_U0->in_stream_a_V_V_empty_n(connect_7_V_V_empty_n);
    FC_1u_500u_10u_U0->in_stream_a_V_V_read(FC_1u_500u_10u_U0_in_stream_a_V_V_read);
    FC_1u_500u_10u_U0->out_stream_V_V_din(FC_1u_500u_10u_U0_out_stream_V_V_din);
    FC_1u_500u_10u_U0->out_stream_V_V_full_n(connect_8_V_V_full_n);
    FC_1u_500u_10u_U0->out_stream_V_V_write(FC_1u_500u_10u_U0_out_stream_V_V_write);
    AXI_DMA_MASTER_U0 = new AXI_DMA_MASTER("AXI_DMA_MASTER_U0");
    AXI_DMA_MASTER_U0->ap_clk(ap_clk);
    AXI_DMA_MASTER_U0->ap_rst(ap_rst_n_inv);
    AXI_DMA_MASTER_U0->ap_start(AXI_DMA_MASTER_U0_ap_start);
    AXI_DMA_MASTER_U0->ap_done(AXI_DMA_MASTER_U0_ap_done);
    AXI_DMA_MASTER_U0->ap_continue(AXI_DMA_MASTER_U0_ap_continue);
    AXI_DMA_MASTER_U0->ap_idle(AXI_DMA_MASTER_U0_ap_idle);
    AXI_DMA_MASTER_U0->ap_ready(AXI_DMA_MASTER_U0_ap_ready);
    AXI_DMA_MASTER_U0->in_stream_V_V_dout(connect_8_V_V_dout);
    AXI_DMA_MASTER_U0->in_stream_V_V_empty_n(connect_8_V_V_empty_n);
    AXI_DMA_MASTER_U0->in_stream_V_V_read(AXI_DMA_MASTER_U0_in_stream_V_V_read);
    AXI_DMA_MASTER_U0->out_stream_TDATA(AXI_DMA_MASTER_U0_out_stream_TDATA);
    AXI_DMA_MASTER_U0->out_stream_TVALID(AXI_DMA_MASTER_U0_out_stream_TVALID);
    AXI_DMA_MASTER_U0->out_stream_TREADY(out_stream_TREADY);
    AXI_DMA_MASTER_U0->out_stream_TLAST(AXI_DMA_MASTER_U0_out_stream_TLAST);
    connect_0_V_V_U = new fifo_w32_d50_A("connect_0_V_V_U");
    connect_0_V_V_U->clk(ap_clk);
    connect_0_V_V_U->reset(ap_rst_n_inv);
    connect_0_V_V_U->if_read_ce(ap_var_for_const0);
    connect_0_V_V_U->if_write_ce(ap_var_for_const0);
    connect_0_V_V_U->if_din(AXI_DMA_SLAVE_U0_out_stream_V_V_din);
    connect_0_V_V_U->if_full_n(connect_0_V_V_full_n);
    connect_0_V_V_U->if_write(AXI_DMA_SLAVE_U0_out_stream_V_V_write);
    connect_0_V_V_U->if_dout(connect_0_V_V_dout);
    connect_0_V_V_U->if_empty_n(connect_0_V_V_empty_n);
    connect_0_V_V_U->if_read(SCIG_1_U0_in_V_V_read);
    connect_1_V_V_U = new fifo_w32_d50_A("connect_1_V_V_U");
    connect_1_V_V_U->clk(ap_clk);
    connect_1_V_V_U->reset(ap_rst_n_inv);
    connect_1_V_V_U->if_read_ce(ap_var_for_const0);
    connect_1_V_V_U->if_write_ce(ap_var_for_const0);
    connect_1_V_V_U->if_din(SCIG_1_U0_out_V_V_din);
    connect_1_V_V_U->if_full_n(connect_1_V_V_full_n);
    connect_1_V_V_U->if_write(SCIG_1_U0_out_V_V_write);
    connect_1_V_V_U->if_dout(connect_1_V_V_dout);
    connect_1_V_V_U->if_empty_n(connect_1_V_V_empty_n);
    connect_1_V_V_U->if_read(SMM_1u_25u_20u_U0_in_stream_a_V_V_read);
    connect_2_V_V_U = new fifo_w32_d2_A("connect_2_V_V_U");
    connect_2_V_V_U->clk(ap_clk);
    connect_2_V_V_U->reset(ap_rst_n_inv);
    connect_2_V_V_U->if_read_ce(ap_var_for_const0);
    connect_2_V_V_U->if_write_ce(ap_var_for_const0);
    connect_2_V_V_U->if_din(SMM_1u_25u_20u_U0_out_stream_V_V_din);
    connect_2_V_V_U->if_full_n(connect_2_V_V_full_n);
    connect_2_V_V_U->if_write(SMM_1u_25u_20u_U0_out_stream_V_V_write);
    connect_2_V_V_U->if_dout(connect_2_V_V_dout);
    connect_2_V_V_U->if_empty_n(connect_2_V_V_empty_n);
    connect_2_V_V_U->if_read(pool_2u_20u_24u_U0_in_V_V_read);
    connect_3_V_V_U = new fifo_w32_d50_A("connect_3_V_V_U");
    connect_3_V_V_U->clk(ap_clk);
    connect_3_V_V_U->reset(ap_rst_n_inv);
    connect_3_V_V_U->if_read_ce(ap_var_for_const0);
    connect_3_V_V_U->if_write_ce(ap_var_for_const0);
    connect_3_V_V_U->if_din(pool_2u_20u_24u_U0_out_V_V_din);
    connect_3_V_V_U->if_full_n(connect_3_V_V_full_n);
    connect_3_V_V_U->if_write(pool_2u_20u_24u_U0_out_V_V_write);
    connect_3_V_V_U->if_dout(connect_3_V_V_dout);
    connect_3_V_V_U->if_empty_n(connect_3_V_V_empty_n);
    connect_3_V_V_U->if_read(SCIG_U0_in_V_V_read);
    connect_4_V_V_U = new fifo_w32_d50_A("connect_4_V_V_U");
    connect_4_V_V_U->clk(ap_clk);
    connect_4_V_V_U->reset(ap_rst_n_inv);
    connect_4_V_V_U->if_read_ce(ap_var_for_const0);
    connect_4_V_V_U->if_write_ce(ap_var_for_const0);
    connect_4_V_V_U->if_din(SCIG_U0_out_V_V_din);
    connect_4_V_V_U->if_full_n(connect_4_V_V_full_n);
    connect_4_V_V_U->if_write(SCIG_U0_out_V_V_write);
    connect_4_V_V_U->if_dout(connect_4_V_V_dout);
    connect_4_V_V_U->if_empty_n(connect_4_V_V_empty_n);
    connect_4_V_V_U->if_read(SMM_1u_500u_50u_U0_in_stream_a_V_V_read);
    connect_5_V_V_U = new fifo_w32_d2_A("connect_5_V_V_U");
    connect_5_V_V_U->clk(ap_clk);
    connect_5_V_V_U->reset(ap_rst_n_inv);
    connect_5_V_V_U->if_read_ce(ap_var_for_const0);
    connect_5_V_V_U->if_write_ce(ap_var_for_const0);
    connect_5_V_V_U->if_din(SMM_1u_500u_50u_U0_out_stream_V_V_din);
    connect_5_V_V_U->if_full_n(connect_5_V_V_full_n);
    connect_5_V_V_U->if_write(SMM_1u_500u_50u_U0_out_stream_V_V_write);
    connect_5_V_V_U->if_dout(connect_5_V_V_dout);
    connect_5_V_V_U->if_empty_n(connect_5_V_V_empty_n);
    connect_5_V_V_U->if_read(pool_2u_50u_8u_U0_in_V_V_read);
    connect_6_V_V_U = new fifo_w32_d50_A("connect_6_V_V_U");
    connect_6_V_V_U->clk(ap_clk);
    connect_6_V_V_U->reset(ap_rst_n_inv);
    connect_6_V_V_U->if_read_ce(ap_var_for_const0);
    connect_6_V_V_U->if_write_ce(ap_var_for_const0);
    connect_6_V_V_U->if_din(pool_2u_50u_8u_U0_out_V_V_din);
    connect_6_V_V_U->if_full_n(connect_6_V_V_full_n);
    connect_6_V_V_U->if_write(pool_2u_50u_8u_U0_out_V_V_write);
    connect_6_V_V_U->if_dout(connect_6_V_V_dout);
    connect_6_V_V_U->if_empty_n(connect_6_V_V_empty_n);
    connect_6_V_V_U->if_read(FC_1u_800u_500u_U0_in_stream_a_V_V_read);
    connect_7_V_V_U = new fifo_w32_d50_A("connect_7_V_V_U");
    connect_7_V_V_U->clk(ap_clk);
    connect_7_V_V_U->reset(ap_rst_n_inv);
    connect_7_V_V_U->if_read_ce(ap_var_for_const0);
    connect_7_V_V_U->if_write_ce(ap_var_for_const0);
    connect_7_V_V_U->if_din(FC_1u_800u_500u_U0_out_stream_V_V_din);
    connect_7_V_V_U->if_full_n(connect_7_V_V_full_n);
    connect_7_V_V_U->if_write(FC_1u_800u_500u_U0_out_stream_V_V_write);
    connect_7_V_V_U->if_dout(connect_7_V_V_dout);
    connect_7_V_V_U->if_empty_n(connect_7_V_V_empty_n);
    connect_7_V_V_U->if_read(FC_1u_500u_10u_U0_in_stream_a_V_V_read);
    connect_8_V_V_U = new fifo_w32_d50_A("connect_8_V_V_U");
    connect_8_V_V_U->clk(ap_clk);
    connect_8_V_V_U->reset(ap_rst_n_inv);
    connect_8_V_V_U->if_read_ce(ap_var_for_const0);
    connect_8_V_V_U->if_write_ce(ap_var_for_const0);
    connect_8_V_V_U->if_din(FC_1u_500u_10u_U0_out_stream_V_V_din);
    connect_8_V_V_U->if_full_n(connect_8_V_V_full_n);
    connect_8_V_V_U->if_write(FC_1u_500u_10u_U0_out_stream_V_V_write);
    connect_8_V_V_U->if_dout(connect_8_V_V_dout);
    connect_8_V_V_U->if_empty_n(connect_8_V_V_empty_n);
    connect_8_V_V_U->if_read(AXI_DMA_MASTER_U0_in_stream_V_V_read);
    start_for_SCIG_1_U0_U = new start_for_SCIG_1_U0("start_for_SCIG_1_U0_U");
    start_for_SCIG_1_U0_U->clk(ap_clk);
    start_for_SCIG_1_U0_U->reset(ap_rst_n_inv);
    start_for_SCIG_1_U0_U->if_read_ce(ap_var_for_const0);
    start_for_SCIG_1_U0_U->if_write_ce(ap_var_for_const0);
    start_for_SCIG_1_U0_U->if_din(start_for_SCIG_1_U0_din);
    start_for_SCIG_1_U0_U->if_full_n(start_for_SCIG_1_U0_full_n);
    start_for_SCIG_1_U0_U->if_write(AXI_DMA_SLAVE_U0_start_write);
    start_for_SCIG_1_U0_U->if_dout(start_for_SCIG_1_U0_dout);
    start_for_SCIG_1_U0_U->if_empty_n(start_for_SCIG_1_U0_empty_n);
    start_for_SCIG_1_U0_U->if_read(SCIG_1_U0_ap_ready);
    start_for_SMM_1u_c7D_U = new start_for_SMM_1u_c7D("start_for_SMM_1u_c7D_U");
    start_for_SMM_1u_c7D_U->clk(ap_clk);
    start_for_SMM_1u_c7D_U->reset(ap_rst_n_inv);
    start_for_SMM_1u_c7D_U->if_read_ce(ap_var_for_const0);
    start_for_SMM_1u_c7D_U->if_write_ce(ap_var_for_const0);
    start_for_SMM_1u_c7D_U->if_din(start_for_SMM_1u_25u_20u_U0_din);
    start_for_SMM_1u_c7D_U->if_full_n(start_for_SMM_1u_25u_20u_U0_full_n);
    start_for_SMM_1u_c7D_U->if_write(SCIG_1_U0_start_write);
    start_for_SMM_1u_c7D_U->if_dout(start_for_SMM_1u_25u_20u_U0_dout);
    start_for_SMM_1u_c7D_U->if_empty_n(start_for_SMM_1u_25u_20u_U0_empty_n);
    start_for_SMM_1u_c7D_U->if_read(SMM_1u_25u_20u_U0_ap_ready);
    start_for_pool_2uc8D_U = new start_for_pool_2uc8D("start_for_pool_2uc8D_U");
    start_for_pool_2uc8D_U->clk(ap_clk);
    start_for_pool_2uc8D_U->reset(ap_rst_n_inv);
    start_for_pool_2uc8D_U->if_read_ce(ap_var_for_const0);
    start_for_pool_2uc8D_U->if_write_ce(ap_var_for_const0);
    start_for_pool_2uc8D_U->if_din(start_for_pool_2u_20u_24u_U0_din);
    start_for_pool_2uc8D_U->if_full_n(start_for_pool_2u_20u_24u_U0_full_n);
    start_for_pool_2uc8D_U->if_write(SMM_1u_25u_20u_U0_start_write);
    start_for_pool_2uc8D_U->if_dout(start_for_pool_2u_20u_24u_U0_dout);
    start_for_pool_2uc8D_U->if_empty_n(start_for_pool_2u_20u_24u_U0_empty_n);
    start_for_pool_2uc8D_U->if_read(pool_2u_20u_24u_U0_ap_ready);
    start_for_SCIG_U0_U = new start_for_SCIG_U0("start_for_SCIG_U0_U");
    start_for_SCIG_U0_U->clk(ap_clk);
    start_for_SCIG_U0_U->reset(ap_rst_n_inv);
    start_for_SCIG_U0_U->if_read_ce(ap_var_for_const0);
    start_for_SCIG_U0_U->if_write_ce(ap_var_for_const0);
    start_for_SCIG_U0_U->if_din(start_for_SCIG_U0_din);
    start_for_SCIG_U0_U->if_full_n(start_for_SCIG_U0_full_n);
    start_for_SCIG_U0_U->if_write(pool_2u_20u_24u_U0_start_write);
    start_for_SCIG_U0_U->if_dout(start_for_SCIG_U0_dout);
    start_for_SCIG_U0_U->if_empty_n(start_for_SCIG_U0_empty_n);
    start_for_SCIG_U0_U->if_read(SCIG_U0_ap_ready);
    start_for_SMM_1u_c9D_U = new start_for_SMM_1u_c9D("start_for_SMM_1u_c9D_U");
    start_for_SMM_1u_c9D_U->clk(ap_clk);
    start_for_SMM_1u_c9D_U->reset(ap_rst_n_inv);
    start_for_SMM_1u_c9D_U->if_read_ce(ap_var_for_const0);
    start_for_SMM_1u_c9D_U->if_write_ce(ap_var_for_const0);
    start_for_SMM_1u_c9D_U->if_din(start_for_SMM_1u_500u_50u_U0_din);
    start_for_SMM_1u_c9D_U->if_full_n(start_for_SMM_1u_500u_50u_U0_full_n);
    start_for_SMM_1u_c9D_U->if_write(SCIG_U0_start_write);
    start_for_SMM_1u_c9D_U->if_dout(start_for_SMM_1u_500u_50u_U0_dout);
    start_for_SMM_1u_c9D_U->if_empty_n(start_for_SMM_1u_500u_50u_U0_empty_n);
    start_for_SMM_1u_c9D_U->if_read(SMM_1u_500u_50u_U0_ap_ready);
    start_for_pool_2udaE_U = new start_for_pool_2udaE("start_for_pool_2udaE_U");
    start_for_pool_2udaE_U->clk(ap_clk);
    start_for_pool_2udaE_U->reset(ap_rst_n_inv);
    start_for_pool_2udaE_U->if_read_ce(ap_var_for_const0);
    start_for_pool_2udaE_U->if_write_ce(ap_var_for_const0);
    start_for_pool_2udaE_U->if_din(start_for_pool_2u_50u_8u_U0_din);
    start_for_pool_2udaE_U->if_full_n(start_for_pool_2u_50u_8u_U0_full_n);
    start_for_pool_2udaE_U->if_write(SMM_1u_500u_50u_U0_start_write);
    start_for_pool_2udaE_U->if_dout(start_for_pool_2u_50u_8u_U0_dout);
    start_for_pool_2udaE_U->if_empty_n(start_for_pool_2u_50u_8u_U0_empty_n);
    start_for_pool_2udaE_U->if_read(pool_2u_50u_8u_U0_ap_ready);
    start_for_FC_1u_8dbE_U = new start_for_FC_1u_8dbE("start_for_FC_1u_8dbE_U");
    start_for_FC_1u_8dbE_U->clk(ap_clk);
    start_for_FC_1u_8dbE_U->reset(ap_rst_n_inv);
    start_for_FC_1u_8dbE_U->if_read_ce(ap_var_for_const0);
    start_for_FC_1u_8dbE_U->if_write_ce(ap_var_for_const0);
    start_for_FC_1u_8dbE_U->if_din(start_for_FC_1u_800u_500u_U0_din);
    start_for_FC_1u_8dbE_U->if_full_n(start_for_FC_1u_800u_500u_U0_full_n);
    start_for_FC_1u_8dbE_U->if_write(pool_2u_50u_8u_U0_start_write);
    start_for_FC_1u_8dbE_U->if_dout(start_for_FC_1u_800u_500u_U0_dout);
    start_for_FC_1u_8dbE_U->if_empty_n(start_for_FC_1u_800u_500u_U0_empty_n);
    start_for_FC_1u_8dbE_U->if_read(FC_1u_800u_500u_U0_ap_ready);
    start_for_FC_1u_5dcE_U = new start_for_FC_1u_5dcE("start_for_FC_1u_5dcE_U");
    start_for_FC_1u_5dcE_U->clk(ap_clk);
    start_for_FC_1u_5dcE_U->reset(ap_rst_n_inv);
    start_for_FC_1u_5dcE_U->if_read_ce(ap_var_for_const0);
    start_for_FC_1u_5dcE_U->if_write_ce(ap_var_for_const0);
    start_for_FC_1u_5dcE_U->if_din(start_for_FC_1u_500u_10u_U0_din);
    start_for_FC_1u_5dcE_U->if_full_n(start_for_FC_1u_500u_10u_U0_full_n);
    start_for_FC_1u_5dcE_U->if_write(FC_1u_800u_500u_U0_start_write);
    start_for_FC_1u_5dcE_U->if_dout(start_for_FC_1u_500u_10u_U0_dout);
    start_for_FC_1u_5dcE_U->if_empty_n(start_for_FC_1u_500u_10u_U0_empty_n);
    start_for_FC_1u_5dcE_U->if_read(FC_1u_500u_10u_U0_ap_ready);
    start_for_AXI_DMAddE_U = new start_for_AXI_DMAddE("start_for_AXI_DMAddE_U");
    start_for_AXI_DMAddE_U->clk(ap_clk);
    start_for_AXI_DMAddE_U->reset(ap_rst_n_inv);
    start_for_AXI_DMAddE_U->if_read_ce(ap_var_for_const0);
    start_for_AXI_DMAddE_U->if_write_ce(ap_var_for_const0);
    start_for_AXI_DMAddE_U->if_din(start_for_AXI_DMA_MASTER_U0_din);
    start_for_AXI_DMAddE_U->if_full_n(start_for_AXI_DMA_MASTER_U0_full_n);
    start_for_AXI_DMAddE_U->if_write(FC_1u_500u_10u_U0_start_write);
    start_for_AXI_DMAddE_U->if_dout(start_for_AXI_DMA_MASTER_U0_dout);
    start_for_AXI_DMAddE_U->if_empty_n(start_for_AXI_DMA_MASTER_U0_empty_n);
    start_for_AXI_DMAddE_U->if_read(AXI_DMA_MASTER_U0_ap_ready);

    SC_METHOD(thread_AXI_DMA_MASTER_U0_ap_continue);

    SC_METHOD(thread_AXI_DMA_MASTER_U0_ap_start);
    sensitive << ( start_for_AXI_DMA_MASTER_U0_empty_n );

    SC_METHOD(thread_AXI_DMA_MASTER_U0_start_full_n);

    SC_METHOD(thread_AXI_DMA_MASTER_U0_start_write);

    SC_METHOD(thread_AXI_DMA_SLAVE_U0_ap_continue);

    SC_METHOD(thread_AXI_DMA_SLAVE_U0_ap_start);

    SC_METHOD(thread_FC_1u_500u_10u_U0_ap_continue);

    SC_METHOD(thread_FC_1u_500u_10u_U0_ap_start);
    sensitive << ( start_for_FC_1u_500u_10u_U0_empty_n );

    SC_METHOD(thread_FC_1u_800u_500u_U0_ap_continue);

    SC_METHOD(thread_FC_1u_800u_500u_U0_ap_start);
    sensitive << ( start_for_FC_1u_800u_500u_U0_empty_n );

    SC_METHOD(thread_SCIG_1_U0_ap_continue);

    SC_METHOD(thread_SCIG_1_U0_ap_start);
    sensitive << ( start_for_SCIG_1_U0_empty_n );

    SC_METHOD(thread_SCIG_U0_ap_continue);

    SC_METHOD(thread_SCIG_U0_ap_start);
    sensitive << ( start_for_SCIG_U0_empty_n );

    SC_METHOD(thread_SMM_1u_25u_20u_U0_ap_continue);

    SC_METHOD(thread_SMM_1u_25u_20u_U0_ap_start);
    sensitive << ( start_for_SMM_1u_25u_20u_U0_empty_n );

    SC_METHOD(thread_SMM_1u_500u_50u_U0_ap_continue);

    SC_METHOD(thread_SMM_1u_500u_50u_U0_ap_start);
    sensitive << ( start_for_SMM_1u_500u_50u_U0_empty_n );

    SC_METHOD(thread_ap_rst_n_inv);
    sensitive << ( ap_rst_n );

    SC_METHOD(thread_ap_sync_continue);

    SC_METHOD(thread_in_stream_TREADY);
    sensitive << ( AXI_DMA_SLAVE_U0_in_stream_TREADY );

    SC_METHOD(thread_out_stream_TDATA);
    sensitive << ( AXI_DMA_MASTER_U0_out_stream_TDATA );

    SC_METHOD(thread_out_stream_TLAST);
    sensitive << ( AXI_DMA_MASTER_U0_out_stream_TLAST );

    SC_METHOD(thread_out_stream_TVALID);
    sensitive << ( AXI_DMA_MASTER_U0_out_stream_TVALID );

    SC_METHOD(thread_pool_2u_20u_24u_U0_ap_continue);

    SC_METHOD(thread_pool_2u_20u_24u_U0_ap_start);
    sensitive << ( start_for_pool_2u_20u_24u_U0_empty_n );

    SC_METHOD(thread_pool_2u_50u_8u_U0_ap_continue);

    SC_METHOD(thread_pool_2u_50u_8u_U0_ap_start);
    sensitive << ( start_for_pool_2u_50u_8u_U0_empty_n );

    SC_METHOD(thread_start_for_AXI_DMA_MASTER_U0_din);

    SC_METHOD(thread_start_for_FC_1u_500u_10u_U0_din);

    SC_METHOD(thread_start_for_FC_1u_800u_500u_U0_din);

    SC_METHOD(thread_start_for_SCIG_1_U0_din);

    SC_METHOD(thread_start_for_SCIG_U0_din);

    SC_METHOD(thread_start_for_SMM_1u_25u_20u_U0_din);

    SC_METHOD(thread_start_for_SMM_1u_500u_50u_U0_din);

    SC_METHOD(thread_start_for_pool_2u_20u_24u_U0_din);

    SC_METHOD(thread_start_for_pool_2u_50u_8u_U0_din);

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    SC_THREAD(thread_ap_var_for_const0);

    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "lenet_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, in_stream_TDATA, "(port)in_stream_TDATA");
    sc_trace(mVcdFile, in_stream_TLAST, "(port)in_stream_TLAST");
    sc_trace(mVcdFile, out_stream_TDATA, "(port)out_stream_TDATA");
    sc_trace(mVcdFile, out_stream_TLAST, "(port)out_stream_TLAST");
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst_n, "(port)ap_rst_n");
    sc_trace(mVcdFile, in_stream_TVALID, "(port)in_stream_TVALID");
    sc_trace(mVcdFile, in_stream_TREADY, "(port)in_stream_TREADY");
    sc_trace(mVcdFile, out_stream_TVALID, "(port)out_stream_TVALID");
    sc_trace(mVcdFile, out_stream_TREADY, "(port)out_stream_TREADY");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_rst_n_inv, "ap_rst_n_inv");
    sc_trace(mVcdFile, AXI_DMA_SLAVE_U0_ap_start, "AXI_DMA_SLAVE_U0_ap_start");
    sc_trace(mVcdFile, AXI_DMA_SLAVE_U0_ap_done, "AXI_DMA_SLAVE_U0_ap_done");
    sc_trace(mVcdFile, AXI_DMA_SLAVE_U0_ap_continue, "AXI_DMA_SLAVE_U0_ap_continue");
    sc_trace(mVcdFile, AXI_DMA_SLAVE_U0_ap_idle, "AXI_DMA_SLAVE_U0_ap_idle");
    sc_trace(mVcdFile, AXI_DMA_SLAVE_U0_ap_ready, "AXI_DMA_SLAVE_U0_ap_ready");
    sc_trace(mVcdFile, AXI_DMA_SLAVE_U0_start_out, "AXI_DMA_SLAVE_U0_start_out");
    sc_trace(mVcdFile, AXI_DMA_SLAVE_U0_start_write, "AXI_DMA_SLAVE_U0_start_write");
    sc_trace(mVcdFile, AXI_DMA_SLAVE_U0_in_stream_TREADY, "AXI_DMA_SLAVE_U0_in_stream_TREADY");
    sc_trace(mVcdFile, AXI_DMA_SLAVE_U0_out_stream_V_V_din, "AXI_DMA_SLAVE_U0_out_stream_V_V_din");
    sc_trace(mVcdFile, AXI_DMA_SLAVE_U0_out_stream_V_V_write, "AXI_DMA_SLAVE_U0_out_stream_V_V_write");
    sc_trace(mVcdFile, SCIG_1_U0_ap_start, "SCIG_1_U0_ap_start");
    sc_trace(mVcdFile, SCIG_1_U0_ap_done, "SCIG_1_U0_ap_done");
    sc_trace(mVcdFile, SCIG_1_U0_ap_continue, "SCIG_1_U0_ap_continue");
    sc_trace(mVcdFile, SCIG_1_U0_ap_idle, "SCIG_1_U0_ap_idle");
    sc_trace(mVcdFile, SCIG_1_U0_ap_ready, "SCIG_1_U0_ap_ready");
    sc_trace(mVcdFile, SCIG_1_U0_start_out, "SCIG_1_U0_start_out");
    sc_trace(mVcdFile, SCIG_1_U0_start_write, "SCIG_1_U0_start_write");
    sc_trace(mVcdFile, SCIG_1_U0_in_V_V_read, "SCIG_1_U0_in_V_V_read");
    sc_trace(mVcdFile, SCIG_1_U0_out_V_V_din, "SCIG_1_U0_out_V_V_din");
    sc_trace(mVcdFile, SCIG_1_U0_out_V_V_write, "SCIG_1_U0_out_V_V_write");
    sc_trace(mVcdFile, SMM_1u_25u_20u_U0_ap_start, "SMM_1u_25u_20u_U0_ap_start");
    sc_trace(mVcdFile, SMM_1u_25u_20u_U0_ap_done, "SMM_1u_25u_20u_U0_ap_done");
    sc_trace(mVcdFile, SMM_1u_25u_20u_U0_ap_continue, "SMM_1u_25u_20u_U0_ap_continue");
    sc_trace(mVcdFile, SMM_1u_25u_20u_U0_ap_idle, "SMM_1u_25u_20u_U0_ap_idle");
    sc_trace(mVcdFile, SMM_1u_25u_20u_U0_ap_ready, "SMM_1u_25u_20u_U0_ap_ready");
    sc_trace(mVcdFile, SMM_1u_25u_20u_U0_start_out, "SMM_1u_25u_20u_U0_start_out");
    sc_trace(mVcdFile, SMM_1u_25u_20u_U0_start_write, "SMM_1u_25u_20u_U0_start_write");
    sc_trace(mVcdFile, SMM_1u_25u_20u_U0_in_stream_a_V_V_read, "SMM_1u_25u_20u_U0_in_stream_a_V_V_read");
    sc_trace(mVcdFile, SMM_1u_25u_20u_U0_out_stream_V_V_din, "SMM_1u_25u_20u_U0_out_stream_V_V_din");
    sc_trace(mVcdFile, SMM_1u_25u_20u_U0_out_stream_V_V_write, "SMM_1u_25u_20u_U0_out_stream_V_V_write");
    sc_trace(mVcdFile, pool_2u_20u_24u_U0_ap_start, "pool_2u_20u_24u_U0_ap_start");
    sc_trace(mVcdFile, pool_2u_20u_24u_U0_ap_done, "pool_2u_20u_24u_U0_ap_done");
    sc_trace(mVcdFile, pool_2u_20u_24u_U0_ap_continue, "pool_2u_20u_24u_U0_ap_continue");
    sc_trace(mVcdFile, pool_2u_20u_24u_U0_ap_idle, "pool_2u_20u_24u_U0_ap_idle");
    sc_trace(mVcdFile, pool_2u_20u_24u_U0_ap_ready, "pool_2u_20u_24u_U0_ap_ready");
    sc_trace(mVcdFile, pool_2u_20u_24u_U0_start_out, "pool_2u_20u_24u_U0_start_out");
    sc_trace(mVcdFile, pool_2u_20u_24u_U0_start_write, "pool_2u_20u_24u_U0_start_write");
    sc_trace(mVcdFile, pool_2u_20u_24u_U0_in_V_V_read, "pool_2u_20u_24u_U0_in_V_V_read");
    sc_trace(mVcdFile, pool_2u_20u_24u_U0_out_V_V_din, "pool_2u_20u_24u_U0_out_V_V_din");
    sc_trace(mVcdFile, pool_2u_20u_24u_U0_out_V_V_write, "pool_2u_20u_24u_U0_out_V_V_write");
    sc_trace(mVcdFile, SCIG_U0_ap_start, "SCIG_U0_ap_start");
    sc_trace(mVcdFile, SCIG_U0_ap_done, "SCIG_U0_ap_done");
    sc_trace(mVcdFile, SCIG_U0_ap_continue, "SCIG_U0_ap_continue");
    sc_trace(mVcdFile, SCIG_U0_ap_idle, "SCIG_U0_ap_idle");
    sc_trace(mVcdFile, SCIG_U0_ap_ready, "SCIG_U0_ap_ready");
    sc_trace(mVcdFile, SCIG_U0_start_out, "SCIG_U0_start_out");
    sc_trace(mVcdFile, SCIG_U0_start_write, "SCIG_U0_start_write");
    sc_trace(mVcdFile, SCIG_U0_in_V_V_read, "SCIG_U0_in_V_V_read");
    sc_trace(mVcdFile, SCIG_U0_out_V_V_din, "SCIG_U0_out_V_V_din");
    sc_trace(mVcdFile, SCIG_U0_out_V_V_write, "SCIG_U0_out_V_V_write");
    sc_trace(mVcdFile, SMM_1u_500u_50u_U0_ap_start, "SMM_1u_500u_50u_U0_ap_start");
    sc_trace(mVcdFile, SMM_1u_500u_50u_U0_ap_done, "SMM_1u_500u_50u_U0_ap_done");
    sc_trace(mVcdFile, SMM_1u_500u_50u_U0_ap_continue, "SMM_1u_500u_50u_U0_ap_continue");
    sc_trace(mVcdFile, SMM_1u_500u_50u_U0_ap_idle, "SMM_1u_500u_50u_U0_ap_idle");
    sc_trace(mVcdFile, SMM_1u_500u_50u_U0_ap_ready, "SMM_1u_500u_50u_U0_ap_ready");
    sc_trace(mVcdFile, SMM_1u_500u_50u_U0_start_out, "SMM_1u_500u_50u_U0_start_out");
    sc_trace(mVcdFile, SMM_1u_500u_50u_U0_start_write, "SMM_1u_500u_50u_U0_start_write");
    sc_trace(mVcdFile, SMM_1u_500u_50u_U0_in_stream_a_V_V_read, "SMM_1u_500u_50u_U0_in_stream_a_V_V_read");
    sc_trace(mVcdFile, SMM_1u_500u_50u_U0_out_stream_V_V_din, "SMM_1u_500u_50u_U0_out_stream_V_V_din");
    sc_trace(mVcdFile, SMM_1u_500u_50u_U0_out_stream_V_V_write, "SMM_1u_500u_50u_U0_out_stream_V_V_write");
    sc_trace(mVcdFile, pool_2u_50u_8u_U0_ap_start, "pool_2u_50u_8u_U0_ap_start");
    sc_trace(mVcdFile, pool_2u_50u_8u_U0_ap_done, "pool_2u_50u_8u_U0_ap_done");
    sc_trace(mVcdFile, pool_2u_50u_8u_U0_ap_continue, "pool_2u_50u_8u_U0_ap_continue");
    sc_trace(mVcdFile, pool_2u_50u_8u_U0_ap_idle, "pool_2u_50u_8u_U0_ap_idle");
    sc_trace(mVcdFile, pool_2u_50u_8u_U0_ap_ready, "pool_2u_50u_8u_U0_ap_ready");
    sc_trace(mVcdFile, pool_2u_50u_8u_U0_start_out, "pool_2u_50u_8u_U0_start_out");
    sc_trace(mVcdFile, pool_2u_50u_8u_U0_start_write, "pool_2u_50u_8u_U0_start_write");
    sc_trace(mVcdFile, pool_2u_50u_8u_U0_in_V_V_read, "pool_2u_50u_8u_U0_in_V_V_read");
    sc_trace(mVcdFile, pool_2u_50u_8u_U0_out_V_V_din, "pool_2u_50u_8u_U0_out_V_V_din");
    sc_trace(mVcdFile, pool_2u_50u_8u_U0_out_V_V_write, "pool_2u_50u_8u_U0_out_V_V_write");
    sc_trace(mVcdFile, FC_1u_800u_500u_U0_ap_start, "FC_1u_800u_500u_U0_ap_start");
    sc_trace(mVcdFile, FC_1u_800u_500u_U0_ap_done, "FC_1u_800u_500u_U0_ap_done");
    sc_trace(mVcdFile, FC_1u_800u_500u_U0_ap_continue, "FC_1u_800u_500u_U0_ap_continue");
    sc_trace(mVcdFile, FC_1u_800u_500u_U0_ap_idle, "FC_1u_800u_500u_U0_ap_idle");
    sc_trace(mVcdFile, FC_1u_800u_500u_U0_ap_ready, "FC_1u_800u_500u_U0_ap_ready");
    sc_trace(mVcdFile, FC_1u_800u_500u_U0_start_out, "FC_1u_800u_500u_U0_start_out");
    sc_trace(mVcdFile, FC_1u_800u_500u_U0_start_write, "FC_1u_800u_500u_U0_start_write");
    sc_trace(mVcdFile, FC_1u_800u_500u_U0_in_stream_a_V_V_read, "FC_1u_800u_500u_U0_in_stream_a_V_V_read");
    sc_trace(mVcdFile, FC_1u_800u_500u_U0_out_stream_V_V_din, "FC_1u_800u_500u_U0_out_stream_V_V_din");
    sc_trace(mVcdFile, FC_1u_800u_500u_U0_out_stream_V_V_write, "FC_1u_800u_500u_U0_out_stream_V_V_write");
    sc_trace(mVcdFile, FC_1u_500u_10u_U0_ap_start, "FC_1u_500u_10u_U0_ap_start");
    sc_trace(mVcdFile, FC_1u_500u_10u_U0_ap_done, "FC_1u_500u_10u_U0_ap_done");
    sc_trace(mVcdFile, FC_1u_500u_10u_U0_ap_continue, "FC_1u_500u_10u_U0_ap_continue");
    sc_trace(mVcdFile, FC_1u_500u_10u_U0_ap_idle, "FC_1u_500u_10u_U0_ap_idle");
    sc_trace(mVcdFile, FC_1u_500u_10u_U0_ap_ready, "FC_1u_500u_10u_U0_ap_ready");
    sc_trace(mVcdFile, FC_1u_500u_10u_U0_start_out, "FC_1u_500u_10u_U0_start_out");
    sc_trace(mVcdFile, FC_1u_500u_10u_U0_start_write, "FC_1u_500u_10u_U0_start_write");
    sc_trace(mVcdFile, FC_1u_500u_10u_U0_in_stream_a_V_V_read, "FC_1u_500u_10u_U0_in_stream_a_V_V_read");
    sc_trace(mVcdFile, FC_1u_500u_10u_U0_out_stream_V_V_din, "FC_1u_500u_10u_U0_out_stream_V_V_din");
    sc_trace(mVcdFile, FC_1u_500u_10u_U0_out_stream_V_V_write, "FC_1u_500u_10u_U0_out_stream_V_V_write");
    sc_trace(mVcdFile, AXI_DMA_MASTER_U0_ap_start, "AXI_DMA_MASTER_U0_ap_start");
    sc_trace(mVcdFile, AXI_DMA_MASTER_U0_ap_done, "AXI_DMA_MASTER_U0_ap_done");
    sc_trace(mVcdFile, AXI_DMA_MASTER_U0_ap_continue, "AXI_DMA_MASTER_U0_ap_continue");
    sc_trace(mVcdFile, AXI_DMA_MASTER_U0_ap_idle, "AXI_DMA_MASTER_U0_ap_idle");
    sc_trace(mVcdFile, AXI_DMA_MASTER_U0_ap_ready, "AXI_DMA_MASTER_U0_ap_ready");
    sc_trace(mVcdFile, AXI_DMA_MASTER_U0_in_stream_V_V_read, "AXI_DMA_MASTER_U0_in_stream_V_V_read");
    sc_trace(mVcdFile, AXI_DMA_MASTER_U0_out_stream_TDATA, "AXI_DMA_MASTER_U0_out_stream_TDATA");
    sc_trace(mVcdFile, AXI_DMA_MASTER_U0_out_stream_TVALID, "AXI_DMA_MASTER_U0_out_stream_TVALID");
    sc_trace(mVcdFile, AXI_DMA_MASTER_U0_out_stream_TLAST, "AXI_DMA_MASTER_U0_out_stream_TLAST");
    sc_trace(mVcdFile, ap_sync_continue, "ap_sync_continue");
    sc_trace(mVcdFile, connect_0_V_V_full_n, "connect_0_V_V_full_n");
    sc_trace(mVcdFile, connect_0_V_V_dout, "connect_0_V_V_dout");
    sc_trace(mVcdFile, connect_0_V_V_empty_n, "connect_0_V_V_empty_n");
    sc_trace(mVcdFile, connect_1_V_V_full_n, "connect_1_V_V_full_n");
    sc_trace(mVcdFile, connect_1_V_V_dout, "connect_1_V_V_dout");
    sc_trace(mVcdFile, connect_1_V_V_empty_n, "connect_1_V_V_empty_n");
    sc_trace(mVcdFile, connect_2_V_V_full_n, "connect_2_V_V_full_n");
    sc_trace(mVcdFile, connect_2_V_V_dout, "connect_2_V_V_dout");
    sc_trace(mVcdFile, connect_2_V_V_empty_n, "connect_2_V_V_empty_n");
    sc_trace(mVcdFile, connect_3_V_V_full_n, "connect_3_V_V_full_n");
    sc_trace(mVcdFile, connect_3_V_V_dout, "connect_3_V_V_dout");
    sc_trace(mVcdFile, connect_3_V_V_empty_n, "connect_3_V_V_empty_n");
    sc_trace(mVcdFile, connect_4_V_V_full_n, "connect_4_V_V_full_n");
    sc_trace(mVcdFile, connect_4_V_V_dout, "connect_4_V_V_dout");
    sc_trace(mVcdFile, connect_4_V_V_empty_n, "connect_4_V_V_empty_n");
    sc_trace(mVcdFile, connect_5_V_V_full_n, "connect_5_V_V_full_n");
    sc_trace(mVcdFile, connect_5_V_V_dout, "connect_5_V_V_dout");
    sc_trace(mVcdFile, connect_5_V_V_empty_n, "connect_5_V_V_empty_n");
    sc_trace(mVcdFile, connect_6_V_V_full_n, "connect_6_V_V_full_n");
    sc_trace(mVcdFile, connect_6_V_V_dout, "connect_6_V_V_dout");
    sc_trace(mVcdFile, connect_6_V_V_empty_n, "connect_6_V_V_empty_n");
    sc_trace(mVcdFile, connect_7_V_V_full_n, "connect_7_V_V_full_n");
    sc_trace(mVcdFile, connect_7_V_V_dout, "connect_7_V_V_dout");
    sc_trace(mVcdFile, connect_7_V_V_empty_n, "connect_7_V_V_empty_n");
    sc_trace(mVcdFile, connect_8_V_V_full_n, "connect_8_V_V_full_n");
    sc_trace(mVcdFile, connect_8_V_V_dout, "connect_8_V_V_dout");
    sc_trace(mVcdFile, connect_8_V_V_empty_n, "connect_8_V_V_empty_n");
    sc_trace(mVcdFile, start_for_SCIG_1_U0_din, "start_for_SCIG_1_U0_din");
    sc_trace(mVcdFile, start_for_SCIG_1_U0_full_n, "start_for_SCIG_1_U0_full_n");
    sc_trace(mVcdFile, start_for_SCIG_1_U0_dout, "start_for_SCIG_1_U0_dout");
    sc_trace(mVcdFile, start_for_SCIG_1_U0_empty_n, "start_for_SCIG_1_U0_empty_n");
    sc_trace(mVcdFile, start_for_SMM_1u_25u_20u_U0_din, "start_for_SMM_1u_25u_20u_U0_din");
    sc_trace(mVcdFile, start_for_SMM_1u_25u_20u_U0_full_n, "start_for_SMM_1u_25u_20u_U0_full_n");
    sc_trace(mVcdFile, start_for_SMM_1u_25u_20u_U0_dout, "start_for_SMM_1u_25u_20u_U0_dout");
    sc_trace(mVcdFile, start_for_SMM_1u_25u_20u_U0_empty_n, "start_for_SMM_1u_25u_20u_U0_empty_n");
    sc_trace(mVcdFile, start_for_pool_2u_20u_24u_U0_din, "start_for_pool_2u_20u_24u_U0_din");
    sc_trace(mVcdFile, start_for_pool_2u_20u_24u_U0_full_n, "start_for_pool_2u_20u_24u_U0_full_n");
    sc_trace(mVcdFile, start_for_pool_2u_20u_24u_U0_dout, "start_for_pool_2u_20u_24u_U0_dout");
    sc_trace(mVcdFile, start_for_pool_2u_20u_24u_U0_empty_n, "start_for_pool_2u_20u_24u_U0_empty_n");
    sc_trace(mVcdFile, start_for_SCIG_U0_din, "start_for_SCIG_U0_din");
    sc_trace(mVcdFile, start_for_SCIG_U0_full_n, "start_for_SCIG_U0_full_n");
    sc_trace(mVcdFile, start_for_SCIG_U0_dout, "start_for_SCIG_U0_dout");
    sc_trace(mVcdFile, start_for_SCIG_U0_empty_n, "start_for_SCIG_U0_empty_n");
    sc_trace(mVcdFile, start_for_SMM_1u_500u_50u_U0_din, "start_for_SMM_1u_500u_50u_U0_din");
    sc_trace(mVcdFile, start_for_SMM_1u_500u_50u_U0_full_n, "start_for_SMM_1u_500u_50u_U0_full_n");
    sc_trace(mVcdFile, start_for_SMM_1u_500u_50u_U0_dout, "start_for_SMM_1u_500u_50u_U0_dout");
    sc_trace(mVcdFile, start_for_SMM_1u_500u_50u_U0_empty_n, "start_for_SMM_1u_500u_50u_U0_empty_n");
    sc_trace(mVcdFile, start_for_pool_2u_50u_8u_U0_din, "start_for_pool_2u_50u_8u_U0_din");
    sc_trace(mVcdFile, start_for_pool_2u_50u_8u_U0_full_n, "start_for_pool_2u_50u_8u_U0_full_n");
    sc_trace(mVcdFile, start_for_pool_2u_50u_8u_U0_dout, "start_for_pool_2u_50u_8u_U0_dout");
    sc_trace(mVcdFile, start_for_pool_2u_50u_8u_U0_empty_n, "start_for_pool_2u_50u_8u_U0_empty_n");
    sc_trace(mVcdFile, start_for_FC_1u_800u_500u_U0_din, "start_for_FC_1u_800u_500u_U0_din");
    sc_trace(mVcdFile, start_for_FC_1u_800u_500u_U0_full_n, "start_for_FC_1u_800u_500u_U0_full_n");
    sc_trace(mVcdFile, start_for_FC_1u_800u_500u_U0_dout, "start_for_FC_1u_800u_500u_U0_dout");
    sc_trace(mVcdFile, start_for_FC_1u_800u_500u_U0_empty_n, "start_for_FC_1u_800u_500u_U0_empty_n");
    sc_trace(mVcdFile, start_for_FC_1u_500u_10u_U0_din, "start_for_FC_1u_500u_10u_U0_din");
    sc_trace(mVcdFile, start_for_FC_1u_500u_10u_U0_full_n, "start_for_FC_1u_500u_10u_U0_full_n");
    sc_trace(mVcdFile, start_for_FC_1u_500u_10u_U0_dout, "start_for_FC_1u_500u_10u_U0_dout");
    sc_trace(mVcdFile, start_for_FC_1u_500u_10u_U0_empty_n, "start_for_FC_1u_500u_10u_U0_empty_n");
    sc_trace(mVcdFile, start_for_AXI_DMA_MASTER_U0_din, "start_for_AXI_DMA_MASTER_U0_din");
    sc_trace(mVcdFile, start_for_AXI_DMA_MASTER_U0_full_n, "start_for_AXI_DMA_MASTER_U0_full_n");
    sc_trace(mVcdFile, start_for_AXI_DMA_MASTER_U0_dout, "start_for_AXI_DMA_MASTER_U0_dout");
    sc_trace(mVcdFile, start_for_AXI_DMA_MASTER_U0_empty_n, "start_for_AXI_DMA_MASTER_U0_empty_n");
    sc_trace(mVcdFile, AXI_DMA_MASTER_U0_start_full_n, "AXI_DMA_MASTER_U0_start_full_n");
    sc_trace(mVcdFile, AXI_DMA_MASTER_U0_start_write, "AXI_DMA_MASTER_U0_start_write");
#endif

    }
    mHdltvinHandle.open("lenet.hdltvin.dat");
    mHdltvoutHandle.open("lenet.hdltvout.dat");
}

lenet::~lenet() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete AXI_DMA_SLAVE_U0;
    delete SCIG_1_U0;
    delete SMM_1u_25u_20u_U0;
    delete pool_2u_20u_24u_U0;
    delete SCIG_U0;
    delete SMM_1u_500u_50u_U0;
    delete pool_2u_50u_8u_U0;
    delete FC_1u_800u_500u_U0;
    delete FC_1u_500u_10u_U0;
    delete AXI_DMA_MASTER_U0;
    delete connect_0_V_V_U;
    delete connect_1_V_V_U;
    delete connect_2_V_V_U;
    delete connect_3_V_V_U;
    delete connect_4_V_V_U;
    delete connect_5_V_V_U;
    delete connect_6_V_V_U;
    delete connect_7_V_V_U;
    delete connect_8_V_V_U;
    delete start_for_SCIG_1_U0_U;
    delete start_for_SMM_1u_c7D_U;
    delete start_for_pool_2uc8D_U;
    delete start_for_SCIG_U0_U;
    delete start_for_SMM_1u_c9D_U;
    delete start_for_pool_2udaE_U;
    delete start_for_FC_1u_8dbE_U;
    delete start_for_FC_1u_5dcE_U;
    delete start_for_AXI_DMAddE_U;
}

void lenet::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void lenet::thread_AXI_DMA_MASTER_U0_ap_continue() {
    AXI_DMA_MASTER_U0_ap_continue = ap_const_logic_1;
}

void lenet::thread_AXI_DMA_MASTER_U0_ap_start() {
    AXI_DMA_MASTER_U0_ap_start = start_for_AXI_DMA_MASTER_U0_empty_n.read();
}

void lenet::thread_AXI_DMA_MASTER_U0_start_full_n() {
    AXI_DMA_MASTER_U0_start_full_n = ap_const_logic_1;
}

void lenet::thread_AXI_DMA_MASTER_U0_start_write() {
    AXI_DMA_MASTER_U0_start_write = ap_const_logic_0;
}

void lenet::thread_AXI_DMA_SLAVE_U0_ap_continue() {
    AXI_DMA_SLAVE_U0_ap_continue = ap_const_logic_1;
}

void lenet::thread_AXI_DMA_SLAVE_U0_ap_start() {
    AXI_DMA_SLAVE_U0_ap_start = ap_const_logic_1;
}

void lenet::thread_FC_1u_500u_10u_U0_ap_continue() {
    FC_1u_500u_10u_U0_ap_continue = ap_const_logic_1;
}

void lenet::thread_FC_1u_500u_10u_U0_ap_start() {
    FC_1u_500u_10u_U0_ap_start = start_for_FC_1u_500u_10u_U0_empty_n.read();
}

void lenet::thread_FC_1u_800u_500u_U0_ap_continue() {
    FC_1u_800u_500u_U0_ap_continue = ap_const_logic_1;
}

void lenet::thread_FC_1u_800u_500u_U0_ap_start() {
    FC_1u_800u_500u_U0_ap_start = start_for_FC_1u_800u_500u_U0_empty_n.read();
}

void lenet::thread_SCIG_1_U0_ap_continue() {
    SCIG_1_U0_ap_continue = ap_const_logic_1;
}

void lenet::thread_SCIG_1_U0_ap_start() {
    SCIG_1_U0_ap_start = start_for_SCIG_1_U0_empty_n.read();
}

void lenet::thread_SCIG_U0_ap_continue() {
    SCIG_U0_ap_continue = ap_const_logic_1;
}

void lenet::thread_SCIG_U0_ap_start() {
    SCIG_U0_ap_start = start_for_SCIG_U0_empty_n.read();
}

void lenet::thread_SMM_1u_25u_20u_U0_ap_continue() {
    SMM_1u_25u_20u_U0_ap_continue = ap_const_logic_1;
}

void lenet::thread_SMM_1u_25u_20u_U0_ap_start() {
    SMM_1u_25u_20u_U0_ap_start = start_for_SMM_1u_25u_20u_U0_empty_n.read();
}

void lenet::thread_SMM_1u_500u_50u_U0_ap_continue() {
    SMM_1u_500u_50u_U0_ap_continue = ap_const_logic_1;
}

void lenet::thread_SMM_1u_500u_50u_U0_ap_start() {
    SMM_1u_500u_50u_U0_ap_start = start_for_SMM_1u_500u_50u_U0_empty_n.read();
}

void lenet::thread_ap_rst_n_inv() {
    ap_rst_n_inv =  (sc_logic) (~ap_rst_n.read());
}

void lenet::thread_ap_sync_continue() {
    ap_sync_continue = ap_const_logic_0;
}

void lenet::thread_in_stream_TREADY() {
    in_stream_TREADY = AXI_DMA_SLAVE_U0_in_stream_TREADY.read();
}

void lenet::thread_out_stream_TDATA() {
    out_stream_TDATA = AXI_DMA_MASTER_U0_out_stream_TDATA.read();
}

void lenet::thread_out_stream_TLAST() {
    out_stream_TLAST = AXI_DMA_MASTER_U0_out_stream_TLAST.read();
}

void lenet::thread_out_stream_TVALID() {
    out_stream_TVALID = AXI_DMA_MASTER_U0_out_stream_TVALID.read();
}

void lenet::thread_pool_2u_20u_24u_U0_ap_continue() {
    pool_2u_20u_24u_U0_ap_continue = ap_const_logic_1;
}

void lenet::thread_pool_2u_20u_24u_U0_ap_start() {
    pool_2u_20u_24u_U0_ap_start = start_for_pool_2u_20u_24u_U0_empty_n.read();
}

void lenet::thread_pool_2u_50u_8u_U0_ap_continue() {
    pool_2u_50u_8u_U0_ap_continue = ap_const_logic_1;
}

void lenet::thread_pool_2u_50u_8u_U0_ap_start() {
    pool_2u_50u_8u_U0_ap_start = start_for_pool_2u_50u_8u_U0_empty_n.read();
}

void lenet::thread_start_for_AXI_DMA_MASTER_U0_din() {
    start_for_AXI_DMA_MASTER_U0_din =  (sc_lv<1>) (ap_const_logic_1);
}

void lenet::thread_start_for_FC_1u_500u_10u_U0_din() {
    start_for_FC_1u_500u_10u_U0_din =  (sc_lv<1>) (ap_const_logic_1);
}

void lenet::thread_start_for_FC_1u_800u_500u_U0_din() {
    start_for_FC_1u_800u_500u_U0_din =  (sc_lv<1>) (ap_const_logic_1);
}

void lenet::thread_start_for_SCIG_1_U0_din() {
    start_for_SCIG_1_U0_din =  (sc_lv<1>) (ap_const_logic_1);
}

void lenet::thread_start_for_SCIG_U0_din() {
    start_for_SCIG_U0_din =  (sc_lv<1>) (ap_const_logic_1);
}

void lenet::thread_start_for_SMM_1u_25u_20u_U0_din() {
    start_for_SMM_1u_25u_20u_U0_din =  (sc_lv<1>) (ap_const_logic_1);
}

void lenet::thread_start_for_SMM_1u_500u_50u_U0_din() {
    start_for_SMM_1u_500u_50u_U0_din =  (sc_lv<1>) (ap_const_logic_1);
}

void lenet::thread_start_for_pool_2u_20u_24u_U0_din() {
    start_for_pool_2u_20u_24u_U0_din =  (sc_lv<1>) (ap_const_logic_1);
}

void lenet::thread_start_for_pool_2u_50u_8u_U0_din() {
    start_for_pool_2u_50u_8u_U0_din =  (sc_lv<1>) (ap_const_logic_1);
}

void lenet::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"in_stream_TDATA\" :  \"" << in_stream_TDATA.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"in_stream_TLAST\" :  \"" << in_stream_TLAST.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"out_stream_TDATA\" :  \"" << out_stream_TDATA.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_stream_TLAST\" :  \"" << out_stream_TLAST.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_rst_n\" :  \"" << ap_rst_n.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"in_stream_TVALID\" :  \"" << in_stream_TVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"in_stream_TREADY\" :  \"" << in_stream_TREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_stream_TVALID\" :  \"" << out_stream_TVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"out_stream_TREADY\" :  \"" << out_stream_TREADY.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

